# Generated by Django 5.2.7 on 2025-12-11 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/package_images/"
                    ),
                ),
                ("recurring", models.BooleanField(default=True)),
                ("amount", models.FloatField(help_text="In dollars (e.g., 9.99)")),
                (
                    "billing_interval",
                    models.CharField(help_text="e.g., day, month, year", max_length=20),
                ),
                (
                    "interval_count",
                    models.IntegerField(
                        default=1,
                        help_text="Number of intervals (e.g., every 6 months = 6)",
                    ),
                ),
                ("price_id", models.CharField(blank=True, max_length=255, null=True)),
                ("product_id", models.CharField(blank=True, max_length=255, null=True)),
                ("vapi_minutes", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("hold", "Hold"), ("active", "Active")],
                        default="active",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripeEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_customer_id", models.CharField(max_length=255)),
                ("stripe_subscription_id", models.CharField(max_length=255)),
                ("price_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "package_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_interval_count",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                (
                    "latest_invoice",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
