# Generated by Django 5.2.7 on 2025-12-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="vapi_minutes",
        ),
    ]
