# Generated by Django 5.2.7 on 2025-10-21 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workout", "0002_workout_image_workout_video"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Mark if the workout is completed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserWorkoutFQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_duration",
                    models.CharField(
                        blank=True,
                        help_text="Preferred session length, e.g., 30 min, 1 hour",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "days_per_week",
                    models.IntegerField(
                        blank=True,
                        help_text="Preferred number of training days per week",
                        null=True,
                    ),
                ),
                (
                    "training_environment",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Gym, Home, Outdoor",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "equipments_access",
                    models.TextField(
                        blank=True,
                        help_text="List of available equipment, e.g., Dumbbells, Treadmill",
                        null=True,
                    ),
                ),
                (
                    "training_style",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Strength, Cardio, HIIT, Yoga",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "activeness_level",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Beginner, Intermediate, Advanced",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "motivation_factor",
                    models.TextField(
                        blank=True,
                        help_text="Reason or motivation for training, e.g., Weight loss, Muscle gain",
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True,
                        help_text="Upcoming event or goal, e.g., Marathon, Wedding",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "recent_injuries",
                    models.TextField(
                        blank=True,
                        help_text="Describe any recent injuries or physical limitations",
                        null=True,
                    ),
                ),
                (
                    "training_environment_spanish",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("equipments_access_spanish", models.TextField(blank=True, null=True)),
                (
                    "training_style_spanish",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "activeness_level_spanish",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("motivation_factor_spanish", models.TextField(blank=True, null=True)),
                (
                    "event_spanish",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("recent_injuries_spanish", models.TextField(blank=True, null=True)),
                (
                    "profile_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra profile info in JSON format",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_workout_fqas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "series",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of sets performed"
                    ),
                ),
                (
                    "reps",
                    models.PositiveIntegerField(
                        default=10, help_text="Repetitions per set"
                    ),
                ),
                ("rest", models.PositiveIntegerField(help_text="Repetitions per set")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="workoutplan.dailyworkout",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workout.workout",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_completed", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("workout_plan_name", models.CharField(max_length=255)),
                ("workout_plan_name_spanish", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fqa",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_plan",
                        to="workoutplan.userworkoutfqa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dailyworkout",
            name="workout_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_workouts",
                to="workoutplan.workoutplan",
            ),
        ),
    ]
