# Generated by Django 5.2.7 on 2025-10-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workoutplan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userworkoutfqa",
            name="fitness_level",
            field=models.CharField(
                blank=True,
                help_text="Overall fitness level, e.g., Low, Moderate, High",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userworkoutfqa",
            name="fitness_level_spanish",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
