# Generated by Django 5.2.7 on 2025-10-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workoutplan", "0002_userworkoutfqa_fitness_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userworkoutfqa",
            name="doctor_clearance",
            field=models.CharField(
                blank=True,
                help_text="Doctor's clearance or recommendation, e.g., Cleared, Needs check-up",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userworkoutfqa",
            name="doctor_clearance_spanish",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
