# Generated by Django 5.2.7 on 2025-12-08 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISuggestData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calorie_need_daily",
                    models.PositiveIntegerField(help_text="Daily calorie need in Kcal"),
                ),
                (
                    "water_liter",
                    models.FloatField(
                        help_text="Daily water intake recommendation in liters"
                    ),
                ),
                (
                    "sleep_duration",
                    models.DurationField(help_text="Total recommended sleep duration"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggest_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
