# Generated by Django 5.2.7 on 2025-10-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('exercise_type', models.CharField(blank=True, max_length=50, null=True)),
                ('workout_name', models.CharField(blank=True, max_length=100, null=True)),
                ('exercise_type_spanish', models.CharField(blank=True, max_length=50, null=True)),
                ('workout_name_spanish', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
