# Generated by Django 5.2.7 on 2025-10-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/workouts/images/'),
        ),
        migrations.AddField(
            model_name='workout',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/workouts/videos/'),
        ),
    ]
