# Generated by Django 5.2.7 on 2025-10-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("subcategory", models.CharField(max_length=100)),
                ("food_name", models.CharField(max_length=255)),
                (
                    "category_spanish",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "subcategory_spanish",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "food_name_spanish",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/meals/image"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
