# Generated by Django 5.2.7 on 2025-10-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="subcategory_spanish",
        ),
    ]
