# Generated by Django 5.2.7 on 2025-10-27 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMealFQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activeness_level",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Beginner, Intermediate, Advanced",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True,
                        help_text="Upcoming event or goal, e.g., Marathon, Wedding",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "doctor_clearance",
                    models.CharField(
                        blank=True,
                        help_text="Doctor's clearance or recommendation, e.g., Cleared, Needs check-up",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "training_environment",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Gym, Home, Outdoor",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "preferences",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "skipped",
                    models.TextField(
                        blank=True, help_text="Foods or ingredients to avoid", null=True
                    ),
                ),
                (
                    "activeness_level_spanish",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "event_spanish",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "doctor_clearance_spanish",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "training_environment_spanish",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "preferences_spanish",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("skipped_spanish", models.TextField(blank=True, null=True)),
                ("profile_json", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_meal_fqa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
