# Generated by Django 5.2.7 on 2025-10-27 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0001_initial"),
        ("mealplan", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "completed",
                    models.BooleanField(
                        default=False,
                        help_text="Mark if the meals for the day are completed",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MealEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Mark if the meal was eaten"
                    ),
                ),
                (
                    "grams",
                    models.FloatField(
                        default=0.0, help_text="Total weight of the meal in grams"
                    ),
                ),
                (
                    "calories",
                    models.FloatField(default=0.0, help_text="Total calories in kcal"),
                ),
                (
                    "protein_g",
                    models.FloatField(
                        default=0.0, help_text="Protein content in grams"
                    ),
                ),
                (
                    "fat_g",
                    models.FloatField(default=0.0, help_text="Fat content in grams"),
                ),
                (
                    "carbs_g",
                    models.FloatField(
                        default=0.0, help_text="Carbohydrate content in grams"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="mealplan.dailymeal",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meal.meal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_completed", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("meal_plan_name", models.CharField(max_length=255)),
                (
                    "meal_plan_name_spanish",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fqa",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plan",
                        to="mealplan.usermealfqa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dailymeal",
            name="meal_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_meals",
                to="mealplan.mealplan",
            ),
        ),
    ]
