# Generated by Django 5.2.7 on 2025-10-29 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0002_remove_meal_subcategory_and_more"),
        ("mealplan", "0002_dailymeal_mealentry_mealplan_dailymeal_meal_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("post_entreno", "Post-Entreno"),
                            ("pre_entreno", "Pre-Entreno"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                        ],
                        max_length=20,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_slots",
                        to="mealplan.dailymeal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealSlotEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "grams",
                    models.FloatField(
                        default=0.0, help_text="Total weight of the meal in grams"
                    ),
                ),
                (
                    "calories",
                    models.FloatField(default=0.0, help_text="Total calories in kcal"),
                ),
                (
                    "protein_g",
                    models.FloatField(
                        default=0.0, help_text="Protein content in grams"
                    ),
                ),
                (
                    "fat_g",
                    models.FloatField(default=0.0, help_text="Fat content in grams"),
                ),
                (
                    "carbs_g",
                    models.FloatField(
                        default=0.0, help_text="Carbohydrate content in grams"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meal.meal",
                    ),
                ),
                (
                    "meal_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="mealplan.mealslot",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MealEntry",
        ),
    ]
