# Generated by Django 5.2.7 on 2025-11-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealplan", "0003_mealslot_mealslotentry_delete_mealentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealslot",
            name="slot_type",
            field=models.CharField(
                choices=[
                    ("post-entreno", "Post-Entreno"),
                    ("pre-entreno", "Pre-Entreno"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                ],
                max_length=20,
            ),
        ),
    ]
